<?php

namespace App\Helpers\General;

class ImportDataHelper
{
    const TRANSLATE_UNIT = [
        'BUAH',
        'KOTAK',
        'LEMBAR',
        'ROLL',
        'BOTOL',
        'PAK' => 'PACK',
        'BUNGKUS',
        'RIM',
        'TUBE',
        'SET',
        'BOX',
        'UNIT',
        'KALENG',
        'KG',
        'PASANG',
        'SACHET',
        'JERIGEN',
        'LITER',
        'BUKU',
        'BATANG',
        'KEPING',
        'METER',
        'LUSIN',
        'PCS',
        'DUS',
        'TABUNG',
        'PACK',
        'PAKET',
        'METER PERSE' => 'METER PERSEGI',
        'BALL',
        'DOOS',
        'KARUNG',
        'SAK',
        'DRUM',
        'LS',
        'PAIL',
        'GALON',
        'STEL',
        'POTONG',
        'EXEMPLAR',
        'BAG',
        'LUNI',
        'IKAT',
        'HURUF',
        'KUBIK',
        'ZAK',
        'METER CUBIC',
        'HIACE',
        'YARD',
        'CAN',
        'EMBER',
        'DUZ',
        'GULUNG',
        'KANTONG',
        'BKS' => 'BUNGKUS',
        'BTR' => 'BUTIR',
        'BH' => 'BUAH',
        'SISIR',
        'KTK' => 'KOTAK',
        'IKT' => 'IKAT',
        'BIJI',
        'KLG' => 'KALENG',
        'BTL' => 'BOTOL',
        'PCH',
        'GLN' => 'GALON',
        'CUP',
        'SCT' => 'SACHET',
        'SCH' => 'SACHET',
        'LBR' => 'LEMBAR',
        'GLG',
        'PC',
        'BKH',
        'PSG' => 'PASANG',
    ];
}
